<?php

namespace SeQura\Core\Tests\BusinessLogic\Common\MockComponents;

use SeQura\Core\BusinessLogic\Domain\Order\Builders\MerchantOrderRequestBuilder;
use SeQura\Core\BusinessLogic\Domain\Order\Models\OrderRequest\Merchant;

/**
 * Class MockMerchantOrderBuilder.
 *
 * @package SeQura\Core\Tests\BusinessLogic\Common\MockComponents
 */
class MockMerchantOrderBuilder extends MerchantOrderRequestBuilder
{
    /**
     * @var Merchant
     */
    private $merchant;

    public function build(string $countryCode, string $cartId): Merchant
    {
        if ($this->merchant) {
            return $this->merchant;
        }

        return parent::build($countryCode, $cartId); // TODO: Change the autogenerated stub
    }

    /**
     * @param Merchant $merchant
     *
     * @return void
     */
    public function setMockMerchant(Merchant $merchant): void
    {
        $this->merchant = $merchant;
    }
}
