name: Update Packagist

on:
  push:

jobs:
  update-packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Packagist
        run: |
          curl -XPOST -H 'Content-Type: application/json' \
          "https://packagist.org/api/update-package?username=sequra&apiToken=${{ secrets.PACKAGIST_API_TOKEN }}" \
          -d '{"repository":{"url":"https://github.com/sequra/integration-core"}}'
