name: phpunit
on: push
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management
    # - uses: php-actions/phpunit@v3
    #   with:
    #     vendored_phpunit_path: "vendor/bin/phpunit"
    #     php_version: "7.2"
    #     configuration: "phpunit.xml"
    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2'
    - run: php vendor/bin/phpunit